export const posts = [
    {
      id: 1,
      title: "Classic Living Room Sofa",
      description: "Perfect for tropical and contemporary styled rooms.Perfect for tropical and contemporary styled rooms.Perfect for tropical and contemporary styled rooms.Perfect for tropical and contemporary styled rooms.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 20,
      rating: 4.2,
      posted: "3 hours ago",
    },
    {
      id: 2,
      title: "Minimalist Beige Sofa",
      description: "Comfortable and stylish furniture for modern homes.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 45,
      rating: 4.8,
      posted: "2 days ago",
    },
    {
      id: 3,
      title: "Elegant Wooden Chair",
      description: "A handcrafted chair designed for durability.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 30,
      rating: 4.5,
      posted: "12 minutes ago",
    },
    {
      id: 4,
      title: "Vintage Sofa Set",
      description: "Luxurious retro-themed furniture for classic interiors.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 18,
      rating: 4.0,
      posted: "1 day ago",
    },
    {
      id: 5,
      title: "Soft Grey Couch",
      description: "A minimalist grey sofa for any living space.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 50,
      rating: 4.9,
      posted: "7 hours ago",
    },
    {
      id: 6,
      title: "Luxury Leather Couch",
      description: "Premium brown leather with hand-stitched finish.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 35,
      rating: 4.6,
      posted: "5 days ago",
    },
    {
      id: 7,
      title: "Modern Sectional Sofa",
      description: "Large L-shaped sofa ideal for family use.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 15,
      rating: 4.1,
      posted: "10 hours ago",
    },
    {
      id: 8,
      title: "Green Velvet Lounge",
      description: "A luxurious velvet sofa with gold details.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 28,
      rating: 4.3,
      posted: "8 minutes ago",
    },
    {
      id: 9,
      title: "Contemporary Sofa Bed",
      description: "Transforms easily into a cozy bed.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 40,
      rating: 4.7,
      posted: "3 days ago",
    },
    {
      id: 10,
      title: "Scandinavian Armchair",
      description: "Lightweight and stylish design with wooden legs.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 22,
      rating: 4.0,
      posted: "35 minutes ago",
    },
    {
      id: 11,
      title: "Compact Reading Sofa",
      description: "A cute small couch ideal for reading nooks.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 27,
      rating: 4.4,
      posted: "6 hours ago",
    },
    {
      id: 12,
      title: "Luxury White Couch",
      description: "A sleek white sofa perfect for minimal setups.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 55,
      rating: 4.9,
      posted: "4 days ago",
    },
    {
      id: 13,
      title: "Soft Pink Lounge Chair",
      description: "Stylish feminine lounge chair with premium fabric.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 16,
      rating: 4.1,
      posted: "9 hours ago",
    },
    {
      id: 14,
      title: "Deep Blue Sofa",
      description: "Bold and modern sofa design.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 33,
      rating: 4.5,
      posted: "22 hours ago",
    },
    {
      id: 15,
      title: "Rustic Brown Sofa",
      description: "Perfect for farmhouse-inspired homes.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 48,
      rating: 4.7,
      posted: "18 minutes ago",
    },
    {
      id: 16,
      title: "Ultra Soft Fabric Sofa",
      description: "Comfortable fabric sofa with deep cushions.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 20,
      rating: 4.2,
      posted: "11 days ago",
    },
    {
      id: 17,
      title: "Curved Modern Couch",
      description: "Unique curved seating for stylish living rooms.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 29,
      rating: 4.3,
      posted: "50 minutes ago",
    },
    {
      id: 18,
      title: "Bright Yellow Sofa",
      description: "A bold color accent piece for any room.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Hard",
      time: 52,
      rating: 4.8,
      posted: "3 hours ago",
    },
    {
      id: 19,
      title: "Arched Back Velvet Sofa",
      description: "A fancy velvet sofa with smooth finish.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Easy",
      time: 25,
      rating: 4.1,
      posted: "2 weeks ago",
    },
    {
      id: 20,
      title: "Ocean Blue Recliner Sofa",
      description: "Recline and relax with premium comfort.",
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      difficulty: "Medium",
      time: 34,
      rating: 4.6,
      posted: "16 hours ago",
    },
  ];
  